<?php

declare(strict_types=1);

namespace Marko\Core\Discovery;

use Marko\Core\Command\CommandDefinition;
use Marko\Core\Container\PreferenceRecord;
use Marko\Core\Event\ObserverDefinition;
use Marko\Core\Exceptions\DiscoveryCacheException;
use Marko\Core\Path\ProjectPaths;
use Marko\Core\Plugin\PluginDefinition;

class DiscoveryCache
{
    public const int CACHE_VERSION = 1;

    public function __construct(
        private readonly ProjectPaths $projectPaths,
        private readonly DiscoveryEnvironment $discoveryEnvironment,
    ) {}

    /**
     * Returns the absolute path to the cache file.
     *
     * A leading '/' (Unix) or a Windows drive letter (e.g. 'C:\') indicates an absolute path;
     * relative paths are resolved against the project base.
     */
    private function resolveCachePath(): string
    {
        $path = $this->discoveryEnvironment->cachePath();

        if ($this->isAbsolutePath($path)) {
            return $path;
        }

        return $this->projectPaths->base . '/' . $path;
    }

    private function isAbsolutePath(string $path): bool
    {
        return str_starts_with($path, '/') || (strlen($path) >= 3 && ctype_alpha($path[0]) && $path[1] === ':');
    }

    /**
     * Returns the absolute path to the cache file (public accessor).
     */
    public function path(): string
    {
        return $this->resolveCachePath();
    }

    /**
     * Returns true if the cache file currently exists.
     */
    public function exists(): bool
    {
        return file_exists($this->resolveCachePath());
    }

    /**
     * Removes the cache file if it exists. Idempotent — safe to call when absent.
     */
    public function clear(): void
    {
        $path = $this->resolveCachePath();
        if (file_exists($path)) {
            unlink($path);
        }
    }

    /**
     * Serializes the discovery payload to a PHP return-array file using var_export.
     *
     * Writes atomically via a temp file in the same directory, then rename().
     *
     * @param array{preferences: PreferenceRecord[], plugins: PluginDefinition[], observers: ObserverDefinition[], commands: CommandDefinition[]} $payload
     *
     * @throws DiscoveryCacheException
     */
    public function write(array $payload): void
    {
        $path = $this->resolveCachePath();
        $dir = dirname($path);

        if (!is_dir($dir) && !@mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw DiscoveryCacheException::notWritable($path);
        }

        $data = [
            'version' => self::CACHE_VERSION,
            'preferences' => array_map(
                fn (PreferenceRecord $r) => [
                    'replacement' => $r->replacement,
                    'replaces' => $r->replaces,
                ],
                $payload['preferences'],
            ),
            'plugins' => array_map(
                fn (PluginDefinition $d) => [
                    'pluginClass' => $d->pluginClass,
                    'targetClass' => $d->targetClass,
                    'beforeMethods' => $d->beforeMethods,
                    'afterMethods' => $d->afterMethods,
                ],
                $payload['plugins'],
            ),
            'observers' => array_map(
                fn (ObserverDefinition $d) => [
                    'observerClass' => $d->observerClass,
                    'eventClass' => $d->eventClass,
                    'priority' => $d->priority,
                    'async' => $d->async,
                ],
                $payload['observers'],
            ),
            'commands' => array_map(
                fn (CommandDefinition $d) => [
                    'commandClass' => $d->commandClass,
                    'name' => $d->name,
                    'description' => $d->description,
                    'aliases' => $d->aliases,
                ],
                $payload['commands'],
            ),
        ];

        $content = "<?php\n\n// This file is generated by Marko — do not edit. Run vendor/bin/marko discovery:clear to remove.\n\nreturn " . var_export(
            $data,
            true,
        ) . ";\n";

        $tmp = $dir . '/.discovery_cache_' . uniqid('', true) . '.tmp';

        if (file_put_contents($tmp, $content) === false) {
            throw DiscoveryCacheException::notWritable($path);
        }

        if (!rename($tmp, $path)) {
            @unlink($tmp);
            throw DiscoveryCacheException::notWritable($path);
        }
    }

    /**
     * Loads and hydrates the cache file into typed value objects.
     *
     * @return array{preferences: PreferenceRecord[], plugins: PluginDefinition[], observers: ObserverDefinition[], commands: CommandDefinition[]}
     *
     * @throws DiscoveryCacheException
     */
    public function load(): array
    {
        $path = $this->resolveCachePath();

        if (!file_exists($path)) {
            throw DiscoveryCacheException::unreadable($path);
        }

        /** @var mixed $data */
        $data = include $path;

        if (!is_array($data)) {
            throw DiscoveryCacheException::malformed($path, 'cache file must return an array');
        }

        $requiredKeys = ['version', 'preferences', 'plugins', 'observers', 'commands'];
        foreach ($requiredKeys as $key) {
            if (!array_key_exists($key, $data)) {
                throw DiscoveryCacheException::malformed($path, "missing required key '$key'");
            }
        }

        if ($data['version'] !== self::CACHE_VERSION) {
            throw DiscoveryCacheException::versionMismatch($path, (int) $data['version'], self::CACHE_VERSION);
        }

        return [
            'preferences' => $this->hydratePreferences($path, $data['preferences']),
            'plugins' => $this->hydratePlugins($path, $data['plugins']),
            'observers' => $this->hydrateObservers($path, $data['observers']),
            'commands' => $this->hydrateCommands($path, $data['commands']),
        ];
    }

    /**
     * @param mixed $records
     * @return PreferenceRecord[]
     *
     * @throws DiscoveryCacheException
     */
    private function hydratePreferences(
        string $path,
        mixed $records,
    ): array {
        if (!is_array($records)) {
            throw DiscoveryCacheException::malformed($path, "'preferences' must be an array");
        }

        $result = [];
        foreach ($records as $i => $record) {
            if (!is_array($record)) {
                throw DiscoveryCacheException::malformed($path, "preferences[$i] must be an array");
            }
            $this->assertStringField($path, $record, 'preferences', $i, 'replacement');
            $this->assertStringField($path, $record, 'preferences', $i, 'replaces');

            $result[] = new PreferenceRecord(
                replacement: $record['replacement'],
                replaces: $record['replaces'],
            );
        }

        return $result;
    }

    /**
     * @param mixed $records
     * @return PluginDefinition[]
     *
     * @throws DiscoveryCacheException
     */
    private function hydratePlugins(
        string $path,
        mixed $records,
    ): array {
        if (!is_array($records)) {
            throw DiscoveryCacheException::malformed($path, "'plugins' must be an array");
        }

        $result = [];
        foreach ($records as $i => $record) {
            if (!is_array($record)) {
                throw DiscoveryCacheException::malformed($path, "plugins[$i] must be an array");
            }
            $this->assertStringField($path, $record, 'plugins', $i, 'pluginClass');
            $this->assertStringField($path, $record, 'plugins', $i, 'targetClass');
            $this->assertArrayField($path, $record, 'plugins', $i, 'beforeMethods');
            $this->assertArrayField($path, $record, 'plugins', $i, 'afterMethods');

            $result[] = new PluginDefinition(
                pluginClass: $record['pluginClass'],
                targetClass: $record['targetClass'],
                beforeMethods: $record['beforeMethods'],
                afterMethods: $record['afterMethods'],
            );
        }

        return $result;
    }

    /**
     * @param mixed $records
     * @return ObserverDefinition[]
     *
     * @throws DiscoveryCacheException
     */
    private function hydrateObservers(
        string $path,
        mixed $records,
    ): array {
        if (!is_array($records)) {
            throw DiscoveryCacheException::malformed($path, "'observers' must be an array");
        }

        $result = [];
        foreach ($records as $i => $record) {
            if (!is_array($record)) {
                throw DiscoveryCacheException::malformed($path, "observers[$i] must be an array");
            }
            $this->assertStringField($path, $record, 'observers', $i, 'observerClass');
            $this->assertStringField($path, $record, 'observers', $i, 'eventClass');
            $this->assertIntField($path, $record, 'observers', $i, 'priority');
            $this->assertBoolField($path, $record, 'observers', $i, 'async');

            $result[] = new ObserverDefinition(
                observerClass: $record['observerClass'],
                eventClass: $record['eventClass'],
                priority: $record['priority'],
                async: $record['async'],
            );
        }

        return $result;
    }

    /**
     * @param mixed $records
     * @return CommandDefinition[]
     *
     * @throws DiscoveryCacheException
     */
    private function hydrateCommands(
        string $path,
        mixed $records,
    ): array {
        if (!is_array($records)) {
            throw DiscoveryCacheException::malformed($path, "'commands' must be an array");
        }

        $result = [];
        foreach ($records as $i => $record) {
            if (!is_array($record)) {
                throw DiscoveryCacheException::malformed($path, "commands[$i] must be an array");
            }
            $this->assertStringField($path, $record, 'commands', $i, 'commandClass');
            $this->assertStringField($path, $record, 'commands', $i, 'name');
            $this->assertStringField($path, $record, 'commands', $i, 'description');
            $this->assertArrayField($path, $record, 'commands', $i, 'aliases');

            $result[] = new CommandDefinition(
                commandClass: $record['commandClass'],
                name: $record['name'],
                description: $record['description'],
                aliases: $record['aliases'],
            );
        }

        return $result;
    }

    /**
     * @param array<mixed> $record
     *
     * @throws DiscoveryCacheException
     */
    private function assertStringField(
        string $path,
        array $record,
        string $section,
        int|string $index,
        string $field,
    ): void {
        if (!array_key_exists($field, $record)) {
            throw DiscoveryCacheException::malformed($path, "$section[$index] missing required field '$field'");
        }
        if (!is_string($record[$field])) {
            throw DiscoveryCacheException::malformed($path, "$section[$index].$field must be a string");
        }
    }

    /**
     * @param array<mixed> $record
     *
     * @throws DiscoveryCacheException
     */
    private function assertArrayField(
        string $path,
        array $record,
        string $section,
        int|string $index,
        string $field,
    ): void {
        if (!array_key_exists($field, $record)) {
            throw DiscoveryCacheException::malformed($path, "$section[$index] missing required field '$field'");
        }
        if (!is_array($record[$field])) {
            throw DiscoveryCacheException::malformed($path, "$section[$index].$field must be an array");
        }
    }

    /**
     * @param array<mixed> $record
     *
     * @throws DiscoveryCacheException
     */
    private function assertIntField(
        string $path,
        array $record,
        string $section,
        int|string $index,
        string $field,
    ): void {
        if (!array_key_exists($field, $record)) {
            throw DiscoveryCacheException::malformed($path, "$section[$index] missing required field '$field'");
        }
        if (!is_int($record[$field])) {
            throw DiscoveryCacheException::malformed($path, "$section[$index].$field must be an int");
        }
    }

    /**
     * @param array<mixed> $record
     *
     * @throws DiscoveryCacheException
     */
    private function assertBoolField(
        string $path,
        array $record,
        string $section,
        int|string $index,
        string $field,
    ): void {
        if (!array_key_exists($field, $record)) {
            throw DiscoveryCacheException::malformed($path, "$section[$index] missing required field '$field'");
        }
        if (!is_bool($record[$field])) {
            throw DiscoveryCacheException::malformed($path, "$section[$index].$field must be a bool");
        }
    }
}
